version: "3.9"
services:
  asics:
    build: .
    restart: always
    command: flask run --host=0.0.0.0 --port=5051
    ports:
      - "5051:5051"
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
