version: "3.9"
services:
  asics:
    build: .
    restart: always
    ports:
      - "5051:5051"
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./cert:/app/cert
